name: registryturbo
resource_size: s
use_dedicated_ip: false
sources:
  goldsky_source:
    dataset_name: stellar_testnet.events
    start_at: 2487
    type: dataset
    version: 1.2.0
transforms:
  transform_1_events:
    primary_key: id
    sql: >-
      --  stellar registry fetch-contract-id registry  
      'CBFFTTX7QKA76FS4LHHQG54BC7JF5RMEX4RTNNJ5KEL76LYHVO3E3OEE' --  stellar
      registry fetch-contract-id unverified
      'CAXY4DZ4OM6XLHGXGWETIHXPJEJKGUZNWSBENC5XHSL3SSMCIO73U7SQ'

      SELECT 
          *,
          CASE 
              WHEN contract_id = 'CBFFTTX7QKA76FS4LHHQG54BC7JF5RMEX4RTNNJ5KEL76LYHVO3E3OEE' THEN 'main'
              WHEN contract_id = 'CAXY4DZ4OM6XLHGXGWETIHXPJEJKGUZNWSBENC5XHSL3SSMCIO73U7SQ' THEN 'unverified'
          END AS channel
      FROM goldsky_source 

      WHERE contract_id IN (
          'CBFFTTX7QKA76FS4LHHQG54BC7JF5RMEX4RTNNJ5KEL76LYHVO3E3OEE', 
          'CAXY4DZ4OM6XLHGXGWETIHXPJEJKGUZNWSBENC5XHSL3SSMCIO73U7SQ'
      ) AND in_successful_contract_call = true  AND transaction_successful =
      true
    type: sql
  transform_2_events_with_command_name:
    primary_key: id
    sql: |-
      select 
        id,
        transaction_hash, 
        ledger_sequence, 
        ledger_closed_at as created_at, 
        JSON_VALUE(topics, '$[0].symbol') as command,
        channel,
        data
      from transform_1_events
    type: sql
  transform_3_deploy_events:
    primary_key: id
    sql: |-
      SELECT 
        id,
        transaction_hash, 
        ledger_sequence, 
        created_at, 
        channel,

        -- WASM Name (Looking for 'wasm_name' key, extracting 'string' value)
        CASE
            WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'wasm_name' 
                THEN JSON_VALUE(data, '$.map[0].val.string')
            WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'wasm_name' 
                THEN JSON_VALUE(data, '$.map[1].val.string')
            WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'wasm_name' 
                THEN JSON_VALUE(data, '$.map[2].val.string')
            WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'wasm_name' 
                THEN JSON_VALUE(data, '$.map[3].val.string')
        END AS wasm_name,

        -- Version (Looking for 'version' key, extracting 'string' value)
        CASE
            WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'version' 
                THEN JSON_VALUE(data, '$.map[0].val.string')
            WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'version' 
                THEN JSON_VALUE(data, '$.map[1].val.string')
            WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'version' 
                THEN JSON_VALUE(data, '$.map[2].val.string')
            WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'version' 
                THEN JSON_VALUE(data, '$.map[3].val.string')
        END AS wasm_version,

        -- Deployer (Looking for 'deployer' key, extracting 'address' value)
        CASE
            WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'deployer' 
                THEN JSON_VALUE(data, '$.map[0].val.address')
            WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'deployer' 
                THEN JSON_VALUE(data, '$.map[1].val.address')
            WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'deployer' 
                THEN JSON_VALUE(data, '$.map[2].val.address')
            WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'deployer' 
                THEN JSON_VALUE(data, '$.map[3].val.address')
        END AS deployer,

        -- Contract ID (Looking for 'contract_id' key, extracting 'address' value)
        CASE
            WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'contract_id' 
                THEN JSON_VALUE(data, '$.map[0].val.address')
            WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'contract_id' 
                THEN JSON_VALUE(data, '$.map[1].val.address')
            WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'contract_id' 
                THEN JSON_VALUE(data, '$.map[2].val.address')
            WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'contract_id' 
                THEN JSON_VALUE(data, '$.map[3].val.address')
        END AS contract_id

      FROM transform_2_events_with_command_name
      WHERE command = 'deploy'
    type: sql
  transform_3_publish_events:
    primary_key: id
    sql: |-
      select 
        id,
        transaction_hash, 
        ledger_sequence, 
        created_at, 
        channel,

      -- Author (Looking for 'author' key, extracting 'address' value)
        CASE
          WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'author' 
            THEN JSON_VALUE(data, '$.map[0].val.address')
          WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'author' 
            THEN JSON_VALUE(data, '$.map[1].val.address')
          WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'author' 
            THEN JSON_VALUE(data, '$.map[2].val.address')
          WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'author' 
            THEN JSON_VALUE(data, '$.map[3].val.address')
        END AS author,

        -- Version (Looking for 'version' key, extracting 'string' value)
        CASE
          WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'version' 
            THEN JSON_VALUE(data, '$.map[0].val.string')
          WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'version' 
            THEN JSON_VALUE(data, '$.map[1].val.string')
          WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'version' 
            THEN JSON_VALUE(data, '$.map[2].val.string')
          WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'version' 
            THEN JSON_VALUE(data, '$.map[3].val.string')
        END AS wasm_version,

        -- WASM Hash (Looking for 'wasm_hash' key, extracting 'bytes' value)
        CASE
          WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'wasm_hash' 
            THEN JSON_VALUE(data, '$.map[0].val.bytes')
          WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'wasm_hash' 
            THEN JSON_VALUE(data, '$.map[1].val.bytes')
          WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'wasm_hash' 
            THEN JSON_VALUE(data, '$.map[2].val.bytes')
          WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'wasm_hash' 
            THEN JSON_VALUE(data, '$.map[3].val.bytes')
        END AS wasm_hash,

        -- WASM Name (Looking for 'wasm_name' key, extracting 'string' value)
        CASE
          WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'wasm_name' 
            THEN JSON_VALUE(data, '$.map[0].val.string')
          WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'wasm_name' 
            THEN JSON_VALUE(data, '$.map[1].val.string')
          WHEN JSON_VALUE(data, '$.map[2].key.symbol') = 'wasm_name' 
            THEN JSON_VALUE(data, '$.map[2].val.string')
          WHEN JSON_VALUE(data, '$.map[3].key.symbol') = 'wasm_name' 
            THEN JSON_VALUE(data, '$.map[3].val.string')
        END AS wasm_name
      from transform_2_events_with_command_name
      where command = 'publish'
    type: sql
  transform_3_register_events:
    primary_key: id
    sql: |-
      SELECT 
          id,
          transaction_hash, 
          ledger_sequence, 
          created_at, 
          channel,

          -- Contract Name (Looking for 'contract_name' key, extracting 'string' value)
          CASE
              WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'contract_name' 
                  THEN JSON_VALUE(data, '$.map[0].val.string')
              WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'contract_name' 
                  THEN JSON_VALUE(data, '$.map[1].val.string')
          END AS contract_name,

          -- Contract ID (Looking for 'contract_id' key, extracting 'address' value)
          CASE
              WHEN JSON_VALUE(data, '$.map[0].key.symbol') = 'contract_id' 
                  THEN JSON_VALUE(data, '$.map[0].val.address')
              WHEN JSON_VALUE(data, '$.map[1].key.symbol') = 'contract_id' 
                  THEN JSON_VALUE(data, '$.map[1].val.address')
          END AS contract_id

      FROM transform_2_events_with_command_name
      WHERE command = 'register'
    type: sql
sinks:
  deploy_events_pg:
    batch_flush_interval: null
    batch_size: null
    from: transform_3_deploy_events
    schema: public
    secret_name: HOSTED_POSTGRES_CMJD1KI8O0
    table: v2_deployed_contracts
    type: postgres
  publish_events_pg:
    batch_flush_interval: null
    batch_size: null
    from: transform_3_publish_events
    schema: public
    secret_name: HOSTED_POSTGRES_CMJD1KI8O0
    table: v2_published_wasms
    type: postgres
  raw_events_backup:
    batch_flush_interval: null
    batch_size: null
    from: transform_1_events
    schema: public
    secret_name: HOSTED_POSTGRES_CMJD1KI8O0
    table: v2_raw_events_backup
    type: postgres
  register_events_pg:
    batch_flush_interval: null
    batch_size: null
    from: transform_3_register_events
    schema: public
    secret_name: HOSTED_POSTGRES_CMJD1KI8O0
    table: v2_registered_contracts
    type: postgres
