// this code was generated by ./bin/generate_scenarios.sh
#[cfg(test)]
mod tests {
    use crate::test::test_get;

    #[actix_web::test]
    async fn test_index_get() {
        test_get(
            "/",
            r#"
        {
          "name": "Registry Indexer API",
          "versions": [
            {
              "path": "/v1",
              "status": "current",
              "version": "v1"
            }
          ]
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_v1_get() {
        test_get(
            "/v1",
            r#"
        {
          "endpoints": [
            {
              "description": "List all published wasms (latest version per name, main channel)",
              "method": "GET",
              "path": "/v1/wasms"
            },
            {
              "description": "Get the latest version of a wasm (main channel)",
              "method": "GET",
              "path": "/v1/wasms/{wasm_name}"
            },
            {
              "description": "Get the latest version of a wasm for a specific channel. Supported channels: main, unverified",
              "method": "GET",
              "path": "/v1/wasms/{channel}/{wasm_name}"
            },
            {
              "description": "Get a specific version of a wasm (main channel)",
              "method": "GET",
              "path": "/v1/wasms/{wasm_name}/v/{version}"
            },
            {
              "description": "Get a specific version of a wasm for a specific channel. Supported channels: main, unverified",
              "method": "GET",
              "path": "/v1/wasms/{channel}/{wasm_name}/v/{version}"
            },
            {
              "description": "List all deployed contracts (main channel)",
              "method": "GET",
              "path": "/v1/contracts"
            },
            {
              "description": "Get details for a deployed contract (main channel)",
              "method": "GET",
              "path": "/v1/contracts/{contract_name}"
            },
            {
              "description": "Get details for a deployed contract for a specific channel. Supported channels: main, unverified",
              "method": "GET",
              "path": "/v1/contracts/{channel}/{contract_name}"
            }
          ],
          "name": "Registry Indexer API v1"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasms_unlimited_get() {
        test_get(
            "/v1/wasms",
            r#"
        {
          "result": [
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "wasm_hash": "6fc19a9ec16b951a66d77a3090de8ac4f06a498805633ea706fdb382ebbca591"
            },
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "channel": "unverified",
              "wasm_version": "1.0.0",
              "wasm_name": "guess-the-number",
              "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist-capped-pausable",
              "wasm_hash": "2fe2f62dd3b89cb2073f558630c4011f70a4315bea5973693af61421e03a1c04"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist-capped",
              "wasm_hash": "ba3cff0c286d45dd79f45094f5450883a9e8961c5b327df4db5d4473296d535f"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist-pausable",
              "wasm_hash": "64d30de2389cb9d62ad501acd7d043c1ba121c1393fa0a94b290c7d8819d97bb"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist",
              "wasm_hash": "9da55f1ed67373665a180bc7b8e1b8ccfd63228c1f14aac2d16a70e56adce50a"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist-capped-pausable",
              "wasm_hash": "5cb190395a612265a5559b1ccb6bfabe4ca322ac5731a712abfc68530c156128"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist-capped",
              "wasm_hash": "4219c2259b9e23245b7ff2d3156e960cc7f66b269d8cee81292edcfb33d29654"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist-pausable",
              "wasm_hash": "16d3ffd85a99bb7bd5449ece82c970578c40559aa79bfc700985020bd25ecfba"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist",
              "wasm_hash": "0fcaed2b9f53b462a43f073b58c94dc82e0d5f03e631f162043df9aa7767dbc6"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-capped-pausable",
              "wasm_hash": "1c56842930f226ea8888600e37ba0bd75287fb4a5b24f831ad2026382ddadcb2"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-capped",
              "wasm_hash": "8fcf68e440d3a96b8c5bab8f36ec72990558cc1758e339492195c39653b0bc6f"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-pausable",
              "wasm_hash": "d90fc032f0d9c3cd989ce2eacbc3735388f052b770dd0d8cc96a46be4f0fa18e"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-standard",
              "wasm_hash": "7856c6e554bfd951cc9a7695e998970e939a439191d1b829444d935b31202df2"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-vault",
              "wasm_hash": "63bfda2216e839f5d1b4b3b1c171f88eb9c31c5eb67e739c0efa41ea1c42ecd3"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-votes-capped-pausable",
              "wasm_hash": "a73df9ebfb6276489508ec47b54bc9b77978784b799c8a81b0099b5fad4de44a"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-votes-capped",
              "wasm_hash": "e4aacf1860ddf3ea4d6d0c9b32ccff3cd6ee5aa8c7e331832d3a1cfc0947f3b7"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-votes-pausable",
              "wasm_hash": "d21c89610d14a617bff747c48376c814a4a4cf65e1cd9c99f3072a4c18795cdc"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-votes",
              "wasm_hash": "0c1db3ef246ae580f01102f6eb5bc63ab7b5ef65628f22c9c42e43d09f5a1ca2"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-consecutive-pausable",
              "wasm_hash": "3d55e5850d64e855520c46d720c9b0b43f3182f65fe8c4aa3fc8c44c4e6ef1db"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-consecutive-royalties-pausable",
              "wasm_hash": "a2c08fb9d740cb040c4af4ccf1fafe54497d3c23eedfeeecc8db049f2c1ade13"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-consecutive-royalties",
              "wasm_hash": "55ecde5527593f1b8fc0c169966238de8318831407901e63d6a2b19ae2ad3aa2"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-consecutive",
              "wasm_hash": "e72cdd125033f702a7382a7648d1f593cf87d81d1f5ab658ef96623f92ecff85"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-enumerable-pausable",
              "wasm_hash": "1edc34e37a06d89130effeb20c17eecf9f8dc32aa21caf5ba37a162076e8b0cc"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-enumerable-royalties-pausable",
              "wasm_hash": "d3b2aec20862382b5d08fb21f92d8392b1ccf527e2fb556e3dc7a862013d043b"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-enumerable-royalties",
              "wasm_hash": "0946e7a4d6d5d3b1eb98bc7c87e41b1cee2331056434ab6f7acc182c126b00f4"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-enumerable",
              "wasm_hash": "80961b97434e6bbc6dd82bf200ee7842d98acce7ad3fa591a8f90c06a8797c00"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-pausable",
              "wasm_hash": "00f53baee396bc329ecb40d8c4201401b79f7a1523431c2329a0b6dee14dfa3f"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-royalties-pausable",
              "wasm_hash": "82ff329cdbff41a33ec2907f7126e241177eaf312ab4efc819591ec27001608a"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-royalties",
              "wasm_hash": "98f8234ce6d7b176925996b19d5ac7b327cd4bbc548987e9645bc85003617bfb"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-nft-standard",
              "wasm_hash": "b759333283c4cff851ead158a17b4856a626d6341686d105810e5ff8a8183194"
            }
          ],
          "next": null
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasms_limit_get() {
        test_get(
            "/v1/wasms?limit=2",
            r#"
        {
          "result": [
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "wasm_hash": "6fc19a9ec16b951a66d77a3090de8ac4f06a498805633ea706fdb382ebbca591"
            },
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "channel": "unverified",
              "wasm_version": "1.0.0",
              "wasm_name": "guess-the-number",
              "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a"
            }
          ],
          "next": "1673107-5c1596d21ae880262f07bb9b539514fd16b384f53c8d8a381375eb5f04aa4e0d-op-0-event-1"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasms_limit_and_cursor_get() {
        test_get(
            "/v1/wasms?limit=2&cursor=1673850-e2a17207280983bdab606afa65fcd52fa8eaeea6dfd5be212de62f2b567390a8-op-0-event-1",
            r#"
        {
          "result": [
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist-capped-pausable",
              "wasm_hash": "5cb190395a612265a5559b1ccb6bfabe4ca322ac5731a712abfc68530c156128"
            },
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "channel": "main",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-blocklist-capped",
              "wasm_hash": "4219c2259b9e23245b7ff2d3156e960cc7f66b269d8cee81292edcfb33d29654"
            }
          ],
          "next": "1673852-caadd455a37f28e0e4b027055483cfcf2dc664115f7e7c971e4e7bca05fde3ac-op-0-event-1"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasm_main_get() {
        test_get(
            "/v1/wasms/oz-ft-allowlist-capped-pausable",
            r#"
        {
          "id": "1673845-e8248d0859629f9bb612cf55254aa92adc96d64ea1c65c2fdf34af948b2c3a3b-op-0-event-1",
          "transaction_hash": "e8248d0859629f9bb612cf55254aa92adc96d64ea1c65c2fdf34af948b2c3a3b",
          "ledger_sequence": 1673845,
          "created_at": "2026-03-24T16:50:19",
          "channel": "main",
          "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
          "wasm_version": "0.6.0",
          "wasm_name": "oz-ft-allowlist-capped-pausable",
          "wasm_hash": "2fe2f62dd3b89cb2073f558630c4011f70a4315bea5973693af61421e03a1c04",
          "versions": [
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist-capped-pausable",
              "wasm_hash": "2fe2f62dd3b89cb2073f558630c4011f70a4315bea5973693af61421e03a1c04"
            }
          ]
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasm_main_versioned_get() {
        test_get(
            "/v1/wasms/oz-ft-allowlist-capped-pausable/v/0.6.0",
            r#"
        {
          "id": "1673845-e8248d0859629f9bb612cf55254aa92adc96d64ea1c65c2fdf34af948b2c3a3b-op-0-event-1",
          "transaction_hash": "e8248d0859629f9bb612cf55254aa92adc96d64ea1c65c2fdf34af948b2c3a3b",
          "ledger_sequence": 1673845,
          "created_at": "2026-03-24T16:50:19",
          "channel": "main",
          "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
          "wasm_version": "0.6.0",
          "wasm_name": "oz-ft-allowlist-capped-pausable",
          "wasm_hash": "2fe2f62dd3b89cb2073f558630c4011f70a4315bea5973693af61421e03a1c04",
          "versions": [
            {
              "author": "GAMPJROHOAW662FINQ4XQOY2ULX5IEGYXCI4SMZYE75EHQBR6PSTJG3M",
              "wasm_version": "0.6.0",
              "wasm_name": "oz-ft-allowlist-capped-pausable",
              "wasm_hash": "2fe2f62dd3b89cb2073f558630c4011f70a4315bea5973693af61421e03a1c04"
            }
          ]
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasm_unverified_get() {
        test_get(
            "/v1/wasms/unverified/guess-the-number",
            r#"
        {
          "id": "1673107-5c1596d21ae880262f07bb9b539514fd16b384f53c8d8a381375eb5f04aa4e0d-op-0-event-1",
          "transaction_hash": "5c1596d21ae880262f07bb9b539514fd16b384f53c8d8a381375eb5f04aa4e0d",
          "ledger_sequence": 1673107,
          "created_at": "2026-03-24T15:48:45",
          "channel": "unverified",
          "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
          "wasm_version": "1.0.0",
          "wasm_name": "guess-the-number",
          "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a",
          "versions": [
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "wasm_version": "1.0.0",
              "wasm_name": "guess-the-number",
              "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a"
            },
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "wasm_version": "0.0.1",
              "wasm_name": "guess-the-number",
              "wasm_hash": "41946348d97e30f03c5975ffe3f5637e8028e74b1fcb3ea38948029860aa0ee4"
            }
          ]
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_wasm_unverified_versioned_get() {
        test_get(
            "/v1/wasms/unverified/guess-the-number/v/1.0.0",
            r#"
        {
          "id": "1673107-5c1596d21ae880262f07bb9b539514fd16b384f53c8d8a381375eb5f04aa4e0d-op-0-event-1",
          "transaction_hash": "5c1596d21ae880262f07bb9b539514fd16b384f53c8d8a381375eb5f04aa4e0d",
          "ledger_sequence": 1673107,
          "created_at": "2026-03-24T15:48:45",
          "channel": "unverified",
          "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
          "wasm_version": "1.0.0",
          "wasm_name": "guess-the-number",
          "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a",
          "versions": [
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "wasm_version": "1.0.0",
              "wasm_name": "guess-the-number",
              "wasm_hash": "f9e4dc04bfda7a0ed2bab1f90669c24d96d7a448e9064c19935ce6d2bef8865a"
            },
            {
              "author": "GCTSUYJBTJ3IHGC5ZMNMM47PQXLKU5EMKLQ5GBMJ24HAXDJSBMLQEQZX",
              "wasm_version": "0.0.1",
              "wasm_name": "guess-the-number",
              "wasm_hash": "41946348d97e30f03c5975ffe3f5637e8028e74b1fcb3ea38948029860aa0ee4"
            }
          ]
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contracts_unlimited_get() {
        test_get(
            "/v1/contracts",
            r#"
        {
          "result": [
            {
              "channel": "main",
              "contract_id": "CAMLHKQHNZO2IOIBFUF5BGZ2V62BMS5QCWFFGRCB4NOB3G5OMDA7SGZN",
              "contract_name": "unverified",
              "deployer": null,
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "contract_name": "registry",
              "deployer": null,
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
              "contract_name": "usdc-circle",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            },
            {
              "channel": "main",
              "contract_id": "CCJUD55AG6W5HAI5LRVNKAE5WDP5XGZBUDS5WNTIVDU7O264UZZE7BRD",
              "contract_name": "soroswap-router",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CDP3HMUH6SMS3S7NPGNDJLULCOXXEPSHY4JKUKMBNQMATHDHWXRRJTBY",
              "contract_name": "soroswap-factory",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CDV6RX4CGPCOKGTBFS52V3LMWQGZN3LCQTXF5RVPOOCG4XVMHXQ4NTF6",
              "contract_name": "blend-pool-factory-v2",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CBDVWXT433PRVTUNM56C3JREF3HIZHRBA64NB2C3B2UNCKIS65ZYCLZA",
              "contract_name": "blend-backstop-v2",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CCEBVDYM32YNYCVNRXQKDFFPISJJCV557CDZEIRBEE4NCV4KHPQ44HGF",
              "contract_name": "blend-testnet-v2-pool",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CAPBMXIQTICKWFPWFDJWMAKBXBPJZUKLNONQH3MLPLLBKQ643CYN5PRW",
              "contract_name": "blend-cetes-pool",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU",
              "contract_name": "usdc-blend",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            },
            {
              "channel": "main",
              "contract_id": "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
              "contract_name": "xlm",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            },
            {
              "channel": "main",
              "contract_id": "CC72F57YTPX76HAA64JQOEGHQAPSADQWSY5DWVBR66JINPFDLNCQYHIC",
              "contract_name": "cetes",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            },
            {
              "channel": "main",
              "contract_id": "CDSCWE4GLNBYYTES2OCYDFQA2LLY4RBIAX6ZI32VSUXD7GO6HRPO4A32",
              "contract_name": "defindex-factory",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CBMVK2JK6NTOT2O4HNQAIQFJY232BHKGLIMXDVQVHIIZKDACXDFZDWHN",
              "contract_name": "defindex-usdc-vault",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CCLV4H7WTLJQ7ATLHBBQV2WW3OINF3FOY5XZ7VPHZO7NH3D2ZS4GFSF6",
              "contract_name": "defindex-xlm-vault",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CBIS5TEMTNNOTBE3WXPQUAGUEDYZZVIWAKTXEQCOUJ34OJJ3FJ5NLF2P",
              "contract_name": "defindex-cetes-vault",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CCP4RBDWPRNO2LWO23XFU4BBLGA73J5N3BK7EHRJUHVN33YEMMFB2MBE",
              "contract_name": "defindex-cetes-blend-strategy",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CAXV5XGWGN344QRU43JG36BKOTFRS33MRBF3LG5PPJQIMKFAD5UYKR5B",
              "contract_name": "oz",
              "deployer": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CDTTACFIG4TJXNZV4XG6AFM35OMALOJ6ZP3OOZE3NBTNF46MBTDNVYAY",
              "contract_name": "circle",
              "deployer": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CC4HNYLXTQ24BQBMIG5A4VPKB7BPNKEIDFKDTI2OZXKRGYU4WXKAD4V7",
              "contract_name": "soroswap",
              "deployer": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CCFSY7TO5UA3B4YZTBYUC6OASCSGVARLJKPYCGP3GY5AJMAME6LWV2P7",
              "contract_name": "blend",
              "deployer": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            },
            {
              "channel": "main",
              "contract_id": "CBFL7TYEYEWSJSBKDP3V5QAEAOJBXTGSQXO6DTIZMQQNCZ64VJG6CMSG",
              "contract_name": "defindex",
              "deployer": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            }
          ],
          "next": null
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contract_get() {
        test_get(
            "/v1/contracts/registry",
            r#"
        {
          "id": "1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-4",
          "transaction_hash": "0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063",
          "ledger_sequence": 1589244,
          "created_at": "2026-03-19T19:12:06",
          "channel": "main",
          "contract_id": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
          "contract_name": "registry",
          "deployer": null,
          "wasm_version": "0.4.1",
          "wasm_name": "registry",
          "is_stellar_asset_contract": false
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contracts_pagination_advanced_1_get() {
        test_get(
            "/v1/contracts?limit=1",
            r#"
        {
          "result": [
            {
              "channel": "main",
              "contract_id": "CAMLHKQHNZO2IOIBFUF5BGZ2V62BMS5QCWFFGRCB4NOB3G5OMDA7SGZN",
              "contract_name": "unverified",
              "deployer": null,
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            }
          ],
          "next": "1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-3"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contracts_pagination_advanced_2_get() {
        test_get(
            "/v1/contracts?limit=1&cursor=1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-3",
            r#"
        {
          "result": [
            {
              "channel": "main",
              "contract_id": "CCA256DWBJJEEYXAWQHP5N4ZAJ2NW4P5T52LZCGC766Q5XHFVNQBMFZV",
              "contract_name": "registry",
              "deployer": null,
              "wasm_version": "0.4.1",
              "wasm_name": "registry",
              "is_stellar_asset_contract": false
            }
          ],
          "next": "1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-4"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contracts_pagination_advanced_3_get() {
        test_get(
            "/v1/contracts?limit=1&cursor=1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-4",
            r#"
        {
          "result": [
            {
              "channel": "main",
              "contract_id": "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
              "contract_name": "usdc-circle",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            }
          ],
          "next": "1589502-2995d4ccd0edd806ffd4754338f0227d80a3644a893fa0cc6e458c09bb9aa822-op-0-event-1"
        }
        "#,
        )
        .await;
    }

    #[actix_web::test]
    async fn test_contracts_pagination_advanced_4_get() {
        test_get(
            "/v1/contracts?limit=1&cursor=1589244-0b3949bc352607c761fe12a0591d23f454303ba22973b62e4e12b60709cf9063-op-0-event-5",
            r#"
        {
          "result": [
            {
              "channel": "main",
              "contract_id": "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
              "contract_name": "usdc-circle",
              "deployer": null,
              "wasm_version": null,
              "wasm_name": null,
              "is_stellar_asset_contract": true
            }
          ],
          "next": "1589502-2995d4ccd0edd806ffd4754338f0227d80a3644a893fa0cc6e458c09bb9aa822-op-0-event-1"
        }
        "#,
        )
        .await;
    }

}
