#!/usr/bin/env python3
"""Generate golden-response tests from scenarios.toml against a running server.

Requires Python 3.11+ (for tomllib). No third-party dependencies.
Output is emitted all-at-once on success; any fetch failure aborts
non-zero with nothing on stdout, so callers can safely redirect to a file.
"""
import io
import json
import os
import sys
import tomllib
import urllib.parse
import urllib.request


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8")


def build_path(scen) -> str:
    if "path" in scen:
        return scen["path"]
    url = scen["url"]
    params = {k: v for k, v in scen.items() if k != "url"}
    if params:
        return f"{url}?{urllib.parse.urlencode(params)}"
    return url


def main() -> int:
    base_url = "http://localhost:8080"
    script_dir = os.path.dirname(os.path.abspath(__file__))
    toml_path = os.path.join(script_dir, "scenarios.toml")

    with open(toml_path, "rb") as f:
        data = tomllib.load(f)

    scenarios = data.get("scenarios", {})
    buf = io.StringIO()

    buf.write("// this code was generated by ./bin/generate_scenarios.sh\n")
    buf.write("#[cfg(test)]\n")
    buf.write("mod tests {\n")
    buf.write("    use crate::test::test_get;\n\n")

    for name, scen in scenarios.items():
        path = build_path(scen)
        if not path.startswith("/"):
            path = "/" + path

        try:
            response_json = json.loads(fetch(f"{base_url}{path}"))
        except Exception as e:
            print(f"error fetching {path}: {e}", file=sys.stderr)
            return 1

        pretty = json.dumps(response_json, indent=2)
        indented = "\n".join(f"        {line}" for line in pretty.splitlines())

        buf.write(f"""    #[actix_web::test]
    async fn test_{name}_get() {{
        test_get(
            "{path}",
            r#"
{indented}
        "#,
        )
        .await;
    }}

""")

    buf.write("}\n")
    sys.stdout.write(buf.getvalue())
    return 0


if __name__ == "__main__":
    sys.exit(main())
