import yaml
import os
import requests
import json
from urllib.parse import urlencode

def main():
    base_url = "http://localhost:8080"
    script_dir = os.path.dirname(os.path.abspath(__file__))
    yaml_path = os.path.join(script_dir, "scenarios.yaml")

    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)

    scenarios = data.get('scenarios', {})

    # Print the requested header
    print("// this code was generated by ./bin/generate_scenarios.sh")
    print("#[cfg(test)]")
    print("mod tests {")
    print("    use crate::test::test_get;")
    print()

    for name, value in scenarios.items():
        if isinstance(value, str):
            path = value
        elif isinstance(value, dict):
            url = value.get('url', '')
            params = {k: v for k, v in value.items() if k != 'url'}
            if params:
                query_string = urlencode(params)
                path = f"{url}?{query_string}"
            else:
                path = url
        else:
            continue

        if not path.startswith('/'):
            path = '/' + path
            
        full_url = f"{base_url}{path}"
        
        try:
            response = requests.get(full_url)
            response.raise_for_status()
            response_json = response.json()
            pretty_json = json.dumps(response_json, indent=2)
            # Indent the JSON (8 spaces for the content inside r#")
            indented_json = "\n".join([f"        {line}" for line in pretty_json.splitlines()])
        except Exception as e:
            indented_json = f"        // Error fetching data: {e}"

        template = f"""    #[actix_web::test]
    async fn test_{name}_get() {{
        test_get(
            "{path}",
            r#"
{indented_json}
        "#,
        )
        .await;
    }}"""
        print(template)
        print()

    # Close the mod tests block
    print("}")

if __name__ == "__main__":
    main()
